/* global React */
// Feedback forum — the read side of dashboard/lib/feedback.js.
//
// feedback.js is how a visitor SUBMITS feedback against a target (a trade, a
// position, a component, the page). This file is how that feedback comes back
// on-screen, with the local agent's answer attached:
//
//   window.TradeFeedbackThreads  — the discussion under one trade
//                                  (#trade/<key>): every thread filed against
//                                  that trade key or its matching position.
//   window.SystemFeedbackPanel   — feedback filed against a COMPONENT or the
//                                  page. That's a note about the site, not
//                                  about a trade, so it never shows under a
//                                  trade — it collects at the very bottom of
//                                  #options.
//
// One feedback item = one thread. Replies are keyed on the feedback id
// (feedback_threads.py), so two questions about the same trade stay two
// separate conversations and an answer can never land under the wrong one.
//
// Data: window.FEEDBACK_THREADS, generated by
// `python -m social_signals_trader.feedback_cli build` into data-feedback.js
// and overlaid live by lib/live-snapshot.js. Missing/empty is the normal
// cold-start case — every entry point below degrades to "nothing to show".

const FeedbackThreadsHelp = window.Help;

const TYPE_TONE = { bug: "bad", feature: "warn", feedback: "neutral" };
const TYPE_LABEL = { bug: "BUG", feature: "IDEA", feedback: "FEEDBACK" };

function feedbackPayload() {
  const p = window.FEEDBACK_THREADS;
  if (!p || !Array.isArray(p.threads)) return { generatedAt: null, threads: [], counts: {} };
  return p;
}

// "2026-08-09T20:35:04Z" -> "Aug 9, 1:35 PM PDT". Display-only; the raw ISO
// stays on the element title so the exact instant is never lost.
function whenLabel(iso) {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return String(iso);
  return d.toLocaleString("en-US", {
    month: "short", day: "numeric", hour: "numeric", minute: "2-digit",
    timeZone: "America/Los_Angeles", timeZoneName: "short",
  });
}

// A thread belongs to this trade page when it was filed against the trade key
// itself, or against the position that trade opened — the two surfaces use
// different id shapes (tradeKey vs positionFeedbackTarget), so the caller
// passes both and this matches either.
function selectThreads(threads, targets) {
  const wanted = (targets || []).filter((t) => t && t.kind && t.id);
  if (!wanted.length) return [];
  return threads.filter((t) =>
    wanted.some((w) => w.kind === t.targetKind && String(w.id) === String(t.targetId))
  );
}

function systemThreads(threads) {
  return threads.filter((t) => t.scope === "system");
}

// --- rendering -------------------------------------------------------------

function ThreadReply({ reply }) {
  return (
    <li className="fbt-reply">
      <div className="fbt-reply-head">
        <span className="fbt-author">{reply.authorLabel || reply.author}</span>
        <span className="fbt-when" title={reply.createdAt || ""}>{whenLabel(reply.createdAt)}</span>
      </div>
      <p className="fbt-body">{reply.body}</p>
    </li>
  );
}

// One thread = the original message, then its replies, then a Reply control
// that re-opens the SAME feedback form scoped to the SAME target — so a
// visitor's follow-up comes back attached to this trade/component, not to the
// page at large.
function FeedbackThread({ thread }) {
  const tone = TYPE_TONE[thread.type] || "neutral";
  return (
    <article className={`fbt-thread fbt-thread--${thread.answered ? "answered" : "open"}`}>
      <header className="fbt-thread-head">
        <span className={`fbt-badge fbt-badge--${tone}`}>{TYPE_LABEL[thread.type] || "FEEDBACK"}</span>
        <h4 className="fbt-title">{thread.title || "(no title)"}</h4>
        <span className="fbt-when" title={thread.createdAt || ""}>{whenLabel(thread.createdAt)}</span>
        <span className={`fbt-status fbt-status--${thread.answered ? "answered" : "open"}`}>
          {thread.answered ? "answered" : "awaiting reply"}
        </span>
      </header>
      {thread.targetLabel && <p className="fbt-target">about: {thread.targetLabel}</p>}
      <p className="fbt-body">{thread.description}</p>
      {thread.replies.length > 0 && (
        <ul className="fbt-replies">
          {thread.replies.map((r) => <ThreadReply key={r.id} reply={r} />)}
        </ul>
      )}
      {window.FeedbackButton && thread.targetKind && thread.targetId && (
        <div className="fbt-thread-foot">
          <window.FeedbackButton
            target={{ kind: thread.targetKind, id: thread.targetId, label: thread.targetLabel || thread.title }}
          />
          <span className="fbt-hint">reply in this thread</span>
        </div>
      )}
    </article>
  );
}

function ThreadList({ threads, emptyText }) {
  if (!threads.length) return <p className="fbt-empty">{emptyText}</p>;
  return <div className="fbt-list">{threads.map((t) => <FeedbackThread key={t.id} thread={t} />)}</div>;
}

// --- entry points ----------------------------------------------------------

// Discussion under one trade. `targets` is [{kind,id}, …] — the trade key and,
// when the trade is still open, the matching position id.
function TradeFeedbackThreads({ targets }) {
  const payload = feedbackPayload();
  const threads = selectThreads(payload.threads, targets);
  const open = threads.filter((t) => !t.answered).length;
  return (
    <section className="card opt-panel fbt-panel" id="trade-feedback">
      <div className="opt-panel-head">
        <h3 className="opt-panel-title">
          Questions &amp; feedback on this trade
          {FeedbackThreadsHelp && <FeedbackThreadsHelp term="feedback_thread" />}
        </h3>
        <div className="opt-panel-stats">
          <span className="fbt-count">{threads.length} thread{threads.length === 1 ? "" : "s"}</span>
          {open > 0 && <span className="fbt-count fbt-count--open">{open} awaiting reply</span>}
        </div>
      </div>
      <ThreadList
        threads={threads}
        emptyText={"No one has asked about this trade yet. Use the \u{1F4AC} button at the top of the page to ask — answers appear here."}
      />
    </section>
  );
}

// System feedback — component/page-scoped notes about the SITE. Lives at the
// bottom of #options, deliberately away from any single trade.
function SystemFeedbackPanel() {
  const payload = feedbackPayload();
  const threads = systemThreads(payload.threads);
  const open = threads.filter((t) => !t.answered).length;
  return (
    <section className="card opt-panel fbt-panel" id="system-feedback">
      <div className="opt-panel-head">
        <h3 className="opt-panel-title">
          Feedback on the site
          {FeedbackThreadsHelp && <FeedbackThreadsHelp term="system_feedback" />}
        </h3>
        <div className="opt-panel-stats">
          <span className="fbt-count">{threads.length} thread{threads.length === 1 ? "" : "s"}</span>
          {open > 0 && <span className="fbt-count fbt-count--open">{open} awaiting reply</span>}
        </div>
      </div>
      <p className="opts-page-sub fbt-lede">
        Feedback filed against a card or the page itself — how the site reads, not what the fund
        traded. Trade-specific questions live on that trade&rsquo;s own page.
      </p>
      <ThreadList
        threads={threads}
        emptyText={"No site feedback yet. Every card has a \u{1F4AC} button; whatever you send lands here with our answer."}
      />
    </section>
  );
}

window.TradeFeedbackThreads = TradeFeedbackThreads;
window.SystemFeedbackPanel = SystemFeedbackPanel;
window.FeedbackThreadsInternals = { selectThreads, systemThreads, whenLabel, feedbackPayload };
