import { useEffect } from 'react';

export function TermsPage() {
  useEffect(() => {
    document.title = 'Terms of Service — bilko.run';
    return () => { document.title = 'Bilko.run — Tools for Makers Who Ship'; };
  }, []);

  return (
    <section className="max-w-3xl mx-auto px-6 py-16 md:py-24">
      <h1 className="text-3xl font-extrabold text-warm-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-warm-400 mb-10">Last updated: March 29, 2026</p>

      <div className="prose-warm space-y-8 text-warm-700 text-sm leading-relaxed">
        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">1. Acceptance</h2>
          <p>By using bilko.run and its tools (including PageRoast), you agree to these terms. If you don't agree, don't use the service.</p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">2. The Service</h2>
          <p>bilko.run provides AI-powered analysis tools. PageRoast fetches publicly accessible web pages and generates conversion scores and feedback using AI (Google Gemini). Results are generated by AI and should be used as guidance, not definitive assessments.</p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">3. Accounts</h2>
          <p>You must sign in via Clerk (Google or email) to use PageRoast. You're responsible for your account. One account per person. Don't share credentials.</p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">4. Credits & Payments</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>New accounts receive 1 free credit.</li>
            <li>Additional credits: $5 for 5 credits (one-time purchase via Stripe).</li>
            <li>PageRoast analysis: 1 credit. A/B Compare: 2 credits.</li>
            <li>Credits do not expire.</li>
            <li><strong>All purchases are final. No refunds.</strong> Credits are consumed immediately upon analysis.</li>
            <li>We reserve the right to change pricing with notice.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 mt-1 space-y-1">
            <li>Submit URLs to private, internal, or unauthorized systems.</li>
            <li>Use the service to harass, defame, or attack businesses or individuals.</li>
            <li>Automate requests or scrape the service without permission.</li>
            <li>Attempt to bypass authentication, credit limits, or security controls.</li>
            <li>Submit content that violates applicable laws.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">6. AI-Generated Content</h2>
          <p>Roast results, scores, and feedback are generated by AI. They are opinions generated by a machine, not professional advice. bilko.run is not responsible for the accuracy, tone, or impact of AI-generated roasts. Share results at your own discretion.</p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">7. Wall of Shame</h2>
          <p>By using PageRoast, you agree that your roast results (domain, score, grade, and roast line) may be displayed anonymously on the public Wall of Shame feed. No personal information (email, name) is displayed.</p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">8. Intellectual Property</h2>
          <p>The bilko.run service, code, and branding are owned by Bilko (Stanislav Bibitkov). You retain ownership of your content. By submitting URLs, you grant us a temporary license to fetch and analyze the publicly accessible content of those pages.</p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">9. No Warranty</h2>
          <p>The service is provided "as is" without warranties of any kind. We don't guarantee uptime, accuracy, or availability. AI analysis may produce unexpected, inaccurate, or humorous results.</p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">10. Limitation of Liability</h2>
          <p>To the fullest extent permitted by law, bilko.run and its operator shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising from your use of the service. Total liability is limited to the amount you paid in the 12 months preceding the claim.</p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">11. Abuse & Termination</h2>
          <p>We may suspend or terminate accounts that violate these terms, abuse the service, or engage in fraudulent activity. Remaining credits are forfeited upon termination for abuse.</p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">12. Changes</h2>
          <p>We may update these terms. Changes take effect when posted. Continued use constitutes acceptance.</p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">13. Governing Law</h2>
          <p>These terms are governed by the laws of the State of Washington, United States, without regard to conflict of law provisions.</p>
        </div>

        <div>
          <h2 className="text-lg font-bold text-warm-900 mb-2">14. Contact</h2>
          <p>Questions about these terms? Email <strong>bilko@bilko.run</strong>.</p>
        </div>
      </div>
    </section>
  );
}
